--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Jorgebyte/FireworksLib
build-by-default: true
branches:
- main
projects:
  FireworksLib:
    path: ""
    model: virion
    type: library
    libs:
      - src: SOF3/await-generator/await-generator
        version: ^3.1.0
      - src: ACM-PocketMine-MP/await-std/await-std
        version: ^0.3.0
...
